In [ ]:
# Essential libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
data= pd.read_excel("/home/sudenur/DYA-project/DYA Anonim Veri.xlsx")

/home/sudenur/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [12]:
data.head()

,se,1- Başvuru Yöntemi,2- Adı Soyadı,Kim Takip Ediyor,3- Telefon,4- Alternatif telefon,5- TC Kimlik No,6- Doğum yılı,7- Eğitim durumu,8- (varsa) Mesleği,...,Unnamed: 1866,Unnamed: 1867,Unnamed: 1868,Unnamed: 1869,Unnamed: 1870,Unnamed: 1871,Unnamed: 1872,Unnamed: 1873,Unnamed: 1874,Unnamed: 1875
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1998,Lise Mezunu,"Tekstil İşçisi, ütücü",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,"Okur yazar, Ortaokul Mezunu",Kağıt ve Diğer Geri Dönüşüm Ürünleri Toplayıcı...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1978,İlkokul terk,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1979,İlkokul,"İşçi / Fabrika işçisi, kapı kolları",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1977,Ortaokul Mezunu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**How many columns?**

In [17]:
len(data.columns)

1876

**Some statistics**

In [18]:
veri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Columns: 1876 entries, se to Unnamed: 1875
dtypes: datetime64[ns](2), float64(1723), object(151)
memory usage: 14.7+ MB

In [6]:
veri.describe()

,se,1- Başvuru Yöntemi,2- Adı Soyadı,Kim Takip Ediyor,3- Telefon,4- Alternatif telefon,5- TC Kimlik No,16- Açık Adres,31- Ad-Soyad,41- Ad-Soyad,...,Unnamed: 1866,Unnamed: 1867,Unnamed: 1868,Unnamed: 1869,Unnamed: 1870,Unnamed: 1871,Unnamed: 1872,Unnamed: 1873,Unnamed: 1874,Unnamed: 1875
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**How many missing values for each column**

In [20]:
veri.isna().sum()

se                    1024
1- Başvuru Yöntemi    1024
2- Adı Soyadı         1024
Kim Takip Ediyor      1024
3- Telefon            1024
                      ...
Unnamed: 1871         1024
Unnamed: 1872         1024
Unnamed: 1873         1024
Unnamed: 1874         1024
Unnamed: 1875         1024
Length: 1876, dtype: int64

**How many unnamed columns are there?**

In [8]:
from re import match
regex = '^Unnamed:.*'
filtered_values = list(filter(lambda v: match(regex, v), veri.columns))

In [9]:
len(filtered_values)

1748

**Dropping unnamed columns**

In [42]:
named_data = veri.drop(filtered_values, axis = 1, inplace = False)

In [26]:
print(f'By dropping unnamed columns, total number of columns decreased from {len(data.columns)} to {len(named_data.columns)}')

By dropping unnamed columns, total number of columns decreased from 1876 to 128

In [25]:
print(f'By dropping unnamed columns, total number of na values decreased from {named_data.isna().sum().sum()} to {veri.isna().sum().sum()}')

By dropping unnamed columns, total number of na values decreased from 103060 to 1891928

**Further process for getting rid of missing values**

Filling name-surname column with index numbers

In [43]:
# renaming '2-Adı Soyadı' column
named_data = named_data.rename(columns={'2-Adı Soyadı': 'Kişiler'})
# filling this column with index starting from one
named_data['Kişiler'] = [i for i in range(1, len(named_data) + 1)]

In [44]:
named_data.head()

,se,1- Başvuru Yöntemi,2- Adı Soyadı,Kim Takip Ediyor,3- Telefon,4- Alternatif telefon,5- TC Kimlik No,6- Doğum yılı,7- Eğitim durumu,8- (varsa) Mesleği,...,117- (borç varsa) Ne kadar?,118- Kovid geçirdiniz mi?,119- Aşı,120- Sağlık Sigortası,121- Yönlendirme yapıldı mı?,122- Özel durum,123- HANEYE İLİŞKİN ÖNEMLİ NOTLAR,124- Kitap Kampanyası,"Yukarıda yapılan açıklamalar çerçevesinde; işbu bilgilendirme ve izin formunu, okuyup, anladığımı ve bu şekilde alınan aşağıdaki beyanımın olduğunu kabul ediyorum. 6698 sayılı Kişisel Verilerin Korunması Kanunu’na uygun olarak kişisel ve/veya özel nitelikli kişisel verilerimin; tamamen veya kısmen elde edilmesi, kaydedilmesi, depolanması, değiştirilmesi, güncellenmesi, periyodik olarak kontrol edilmesi, yeniden düzenlenmesi, sınıflandırılması, işlendikleri amaç için gerekli olan ya da ilgili kanunda öngörülen süre kadar muhafaza edilmesi, kanuni ya da hizmete bağlı fiili gereklilikler halinde sivil toplum kuruluşunuzun birlikte çalıştığı ya da kanunen yükümlü olduğu kamu kurum ve kuruluşlarıyla ve/veya Türkiye’de veya yurt dışında mukim olan 3. kişi destekçiler ile paylaşılması da dâhil olmak üzere yukarıda belirtilen açıklamalar kapsamında işlenmesine, konu hakkında tereddüdeyer vermeyecek şekilde bilgi sahibi ve aydınlatılmış olarak açık rızam ile onay veriyorum.",Kişiler
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1998,Lise Mezunu,"Tekstil İşçisi, ütücü",...,NaN,Hayır,"kaydı olmadığı için aşı olmadı, imkanı varsa o...",NaN,Yapılmadı,NaN,"Çift Afganistandan 2020 de geldi, tekstilde ça...",NaN,"Okuduğumu anladım, onaylıyorum.",1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,"Okur yazar, Ortaokul Mezunu",Kağıt ve Diğer Geri Dönüşüm Ürünleri Toplayıcı...,...,10 bin tl,Bir kere geçirdi,Oldu,Hiçbir sağlık sigortası yok,SYDV,NaN,NaN,NaN,"Okuduğumu anladım, onaylıyorum.",2
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1978,İlkokul terk,NaN,...,8bin,Hayır,Oldu,Yeşil kart,NaN,kanser tedavisi gördüğü için bakıma ihtiyacı var,"televizyon ve çek-yat, yatak, baza acil ihtiya...",Açev Okuyan Bir Gelecek (3-7 yaş),"Okuduğumu anladım, onaylıyorum.",3
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1979,İlkokul,"İşçi / Fabrika işçisi, kapı kolları",...,NaN,NaN,NaN,NaN,NaN,NaN,küçük oğlu veteriner olmak istiyor. kuşları ha...,NaN,"Okuduğumu anladım, onaylamıyorum.",4
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1977,Ortaokul Mezunu,NaN,...,NaN,Bir kere geçirdi,Henüz olmadı ama olacak,SGK,NaN,NaN,İkamet izni kapsamında sağlık sigortası kullan...,Açev Okuyan Bir Gelecek (3-7 yaş),"Okuduğumu anladım, onaylıyorum.",5